[package]
name = "space"
version = "0.1.0"
authors = ["tom barrett <spalf0@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
termion = "*"
rand = "0.6"
toml = "0.4"
clap = "2"
diesel = {version = "1.0.0", features = ["postgres"]}
