-- Your SQL goes here
CREATE TABLE masses (
	id SERIAL PRIMARY KEY,
	name VARCHAR NOT NULL,
	pos_x FLOAT NOT NULL,
	pos_y DOUBLE PRECISION NOT NULL,
	pos_z DOUBLE PRECISION NOT NULL,
	vel_x DOUBLE PRECISION NOT NULL,
	vel_y DOUBLE PRECISION NOT NULL,
	vel_z DOUBLE PRECISION NOT NULL,
	type_data JSONB NOT NULL
)
